syntax = "proto3";

package meshtastic;

option csharp_namespace = "Meshtastic.Protobufs";
option go_package = "github.com/meshtastic/go/generated";
option java_outer_classname = "ModuleConfigProtos";
option java_package = "com.geeksville.mesh";
option swift_prefix = "";

/*
 * This message wraps the header and lower 160 bytes of the payload of a 
 * MAVLink v2 packet
 */

message MavlinkPacket {
    /* Length of the MAVLink payload */
    uint32 length = 1;

    /* (In)Compatibility flags */
    uint32 incompat_flags = 2;
    uint32 compat_flags = 3;

    /* Message sequence number */
    uint32 seq_number = 4;

    /* Sender IDs */
    uint32 system_id = 5;
    uint32 component_id = 6;

    /* Message ID */
    uint32 msg_id = 7;

    /* Checksum */
    uint32 checksum = 8;

    /* Payload */
    optional bytes payload = 9;

    /* Signature */
    optional bytes signature = 10;

}

/* 
 * This message wraps the rest of the packet, if required */

message MavlinkExtendedPacket {
    /* Length of the MAVLink payload */
    uint32 length = 1;

    /* Message sequence number */
    uint32 seq_number = 2;

    /* Sender IDs */
    uint32 system_id = 3;
    uint32 component_id = 4;

    /* Message ID */
    uint32 msg_id = 5;

    /* Payload */
    bytes payload = 6;
}
